// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-embed-files.ts
// Run 'bun run generate:embed' to regenerate

import "../public/assets/index-DDpIYYKL.js" with { type: "file" };
import "../public/assets/index-DfwV4ouo.css" with { type: "file" };
import "../public/index.html" with { type: "file" };
import "../public/favicon.svg" with { type: "file" };

// Re-export for potential use
export {};
